/**
 * Storybook stand-in for vite-plugin-pwa's virtual `virtual:pwa-register/react`
 * module.
 *
 * The real module is generated by the `VitePWA` plugin in the app's Vite config
 * (`registerType: "prompt"`), so it does not exist under Storybook's own Vite
 * config. `pwa-update-prompt.tsx` imports it directly, which is why every story
 * that renders that component needs this alias target.
 *
 * The hook keeps `needRefresh` as real component state, so stories can exercise
 * the prompt's actual interactions — "Update" and "Later" both dismiss the
 * banner, just as they do once a staged update completes or is deferred. The
 * module-scoped `refreshAvailable` flag is read once at mount time; stories
 * that want a specific initial state call `setRefreshAvailable` before
 * rendering.
 */
import { useState } from "react";
import type { Dispatch, SetStateAction } from "react";

type RegisterSWResult = {
  needRefresh: [boolean, Dispatch<SetStateAction<boolean>>];
  offlineReady: [boolean, Dispatch<SetStateAction<boolean>>];
  updateServiceWorker: (reloadPage?: boolean) => Promise<void>;
};

let refreshAvailable = true;

/** Storybook-only: choose whether a waiting service worker exists on next mount. */
export function setRefreshAvailable(value: boolean): void {
  refreshAvailable = value;
}

export function useRegisterSW(): RegisterSWResult {
  const [needRefresh, setNeedRefresh] = useState<boolean>(refreshAvailable);
  const [offlineReady, setOfflineReady] = useState<boolean>(false);

  return {
    needRefresh: [needRefresh, setNeedRefresh],
    offlineReady: [offlineReady, setOfflineReady],
    // The real hook reloads the window once the new worker takes control;
    // dismissing the banner mirrors the completed-update state in the sandbox.
    updateServiceWorker: async () => {
      setNeedRefresh(false);
    },
  };
}
